spring:
  application:
    name: courses-service

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/test/test.db
logging:
  level:
    com.github.raily01.coursesservice: debug